version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: code
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:rw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 5
      timeout: 5s
      interval: 10s

  app:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      mysql:
        condition: "service_healthy"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/code
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  mysql_data: